server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/stefaninidb
    username: stefanini
    password: stefanini123
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      web-allow-others: true
  output:
    ansi:
      enabled: Always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true